p8105\_hw1\_yt2785
================

Problem 1

``` r
library(tidyverse)
```

    ## -- Attaching packages --------------------------------------- tidyverse 1.3.1 --

    ## v ggplot2 3.3.5     v purrr   0.3.4
    ## v tibble  3.1.4     v dplyr   1.0.7
    ## v tidyr   1.1.3     v stringr 1.4.0
    ## v readr   2.0.1     v forcats 0.5.1

    ## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

``` r
random_df = rnorm(10)
logic_vector = random_df > 0
character_vector = c("1","2","3","1","2","3", "1","2","3","2")
factor_vector = factor(c("x","y","z","x","y","z", "x","y","z","y"))
```

``` r
R = mean(random_df)
L = mean(logic_vector)
C = mean(character_vector)
```

    ## Warning in mean.default(character_vector): 参数不是数值也不是逻辑值：回覆NA

``` r
F = mean(factor_vector)
```

    ## Warning in mean.default(factor_vector): 参数不是数值也不是逻辑值：回覆NA

``` r
R
```

    ## [1] -0.1425511

``` r
L
```

    ## [1] 0.4

``` r
C
```

    ## [1] NA

``` r
F
```

    ## [1] NA

``` r
as.numeric(logic_vector)
```

    ##  [1] 1 0 0 0 1 1 1 0 0 0

``` r
as.numeric(character_vector)
```

    ##  [1] 1 2 3 1 2 3 1 2 3 2

``` r
as.numeric(factor_vector)
```

    ##  [1] 1 2 3 1 2 3 1 2 3 2

Problem 2

``` r
library(palmerpenguins)
library(ggplot2)
library(dplyr)
```

``` r
data("penguins", package = "palmerpenguins")
summary(penguins)
```

    ##       species          island    bill_length_mm  bill_depth_mm  
    ##  Adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  
    ##  Chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  
    ##  Gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  
    ##                                  Mean   :43.92   Mean   :17.15  
    ##                                  3rd Qu.:48.50   3rd Qu.:18.70  
    ##                                  Max.   :59.60   Max.   :21.50  
    ##                                  NA's   :2       NA's   :2      
    ##  flipper_length_mm  body_mass_g       sex           year     
    ##  Min.   :172.0     Min.   :2700   female:165   Min.   :2007  
    ##  1st Qu.:190.0     1st Qu.:3550   male  :168   1st Qu.:2007  
    ##  Median :197.0     Median :4050   NA's  : 11   Median :2008  
    ##  Mean   :200.9     Mean   :4202                Mean   :2008  
    ##  3rd Qu.:213.0     3rd Qu.:4750                3rd Qu.:2009  
    ##  Max.   :231.0     Max.   :6300                Max.   :2009  
    ##  NA's   :2         NA's   :2

``` r
n_row = nrow(penguins)
n_col = ncol(penguins)
colnames(penguins)
```

    ## [1] "species"           "island"            "bill_length_mm"   
    ## [4] "bill_depth_mm"     "flipper_length_mm" "body_mass_g"      
    ## [7] "sex"               "year"

``` r
b = pull(penguins, var = flipper_length_mm)
summary(b)
```

    ##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
    ##   172.0   190.0   197.0   200.9   213.0   231.0       2

``` r
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm)) + geom_point(aes(color = species))
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](p8105_hw1_yt2785_files/figure-gfm/unnamed-chunk-6-1.png)<!-- -->

There are 344 rows and 8 columns in the dataset. Including species,
island, bill\_length\_mm, bill\_depth\_mm, flipper\_length\_mm,
body\_mass\_g, sex, year in total 8 variables, and the describtion of
them are Adelie :152 , Chinstrap: 68 , Gentoo :124 , NA, NA, NA, NA,
Biscoe :168 , Dream :124 , Torgersen: 52 , NA, NA, NA, NA, Min. :32.10 ,
1st Qu.:39.23 , Median :44.45 , Mean :43.92 , 3rd Qu.:48.50 , Max.
:59.60 , NA’s :2 , Min. :13.10 , 1st Qu.:15.60 , Median :17.30 , Mean
:17.15 , 3rd Qu.:18.70 , Max. :21.50 , NA’s :2 , Min. :172.0 , 1st
Qu.:190.0 , Median :197.0 , Mean :200.9 , 3rd Qu.:213.0 , Max. :231.0 ,
NA’s :2 , Min. :2700 , 1st Qu.:3550 , Median :4050 , Mean :4202 , 3rd
Qu.:4750 , Max. :6300 , NA’s :2 , female:165 , male :168 , NA’s : 11 ,
NA, NA, NA, NA, Min. :2007 , 1st Qu.:2007 , Median :2008 , Mean :2008 ,
3rd Qu.:2009 , Max. :2009 , NA. The mean of flipper length is 200.9.
