---
title: "p8105_hw1_yt2785"
output: github_document
---

Problem 1

```{r}
library(tidyverse)
```


```{r}
example_df = 
  tibble(
  random_df = rnorm(10),
  vec_log = random_df > 0,
  vec_char = c("Ali","Bieber","Seunghub","Hun","J.don","Jungkok", "Hyuna","V","RM","JH"),
  vec_factor = factor(c("Solo","Solo","N.Fling","N.Flying","N.Flying","BTS", "Solo","BTS","BTS","BTS"))
  )
example_df
```


```{r}
r = pull(example_df, var = random_df)
l = as.numeric(pull(example_df, var = vec_log))
c = as.numeric(pull(example_df, var = vec_char))
f = as.numeric(pull(example_df, var = vec_factor))
R = mean(q)
L = mean(l)
C = mean(c)
F = mean(f)
R
L
C
F
```




Problem 2

```{r}
library(palmerpenguins)
library(ggplot2)
library(dplyr)
```


```{r}
data("penguins", package = "palmerpenguins")
summary(penguins,na.rm=TRUE)
skimr::skim(penguins)
n_row = nrow(penguins)
n_col = ncol(penguins)
colnames(penguins)
b = pull(penguins, var = flipper_length_mm)
mean_flipper = mean(b,na.rm=TRUE)
```

There are `r n_row` rows and `r n_col` columns in the dataset. Including `r colnames(penguins)` in total 8 variables, and the describtion of them are `r summary(penguins)`. The mean of flipper length is `r mean_flipper`.

```{r}
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm)) + geom_point(aes(color = species))
ggsave("penguins_plot.pdf",height = 4,width = 4)
```

